from tkinter import *
raiz=Tk()
raiz.title("Proyecto Hoteles")
#raiz.geometry("650x350")
raiz.config(bg="#d89fca")
frame1=Frame()
frame1.pack()
frame1.config(bg="blue")
frame1.config(width="600", height="300")
frame1.config(cursor="hand2")
frame2=Frame()
frame2.pack()
frame2.config(bg="red")
frame2.config(width="600", height="300")
frame2.config(cursor="pirate")
raiz.mainloop